### ISSUE TITLE
Allow the bombs to explode

### ISSUE THREAD

**Issue by Eugleo** [purescript-course/bomberman#3]
The bombs added in #4 should explode instead of disappearing. During the explosion, which should be a cross spanning 2 tiles from the original place of the bomb, boxes (#3) get destroyed and player (#2) gets hurt.

Specifically:
- [ ] walls (#1) block the explosion
- [ ] box (#3) gets destroyed, but blocks the explosion in that direction onwards
- [ ] player (#2) gets hurt, or killed, whichever you prefer

## Instructions & hints

- The `Bomb` type should contain the information that the bomb is _currently_ exploding (you can do this by simply adding `isExploding :: Boolean`, but there are many options)
- In `draw`, display the exploding bomb as tiles arranged in a cross pattern (`O` is the original place of the bomb):
```
  X
  X
XXOXX
  X
  X
```
  - circular explosions are advised against, because it would be harder to properly implement the "walls block the explosion" feature
- In `handleEvent`, when you encounter a bomb that is exploding, manually check the walls, boxes, and the position of the player, and implement the blocking/destroying/hurting features there
