### ISSUE TITLE
Allow the bombs to explode

### ISSUE THREAD

**Issue by Eugleo** [purescript-course/bomberman#5]
The bombs added in #4 should explode instead of disappearing. During the explosion, which should be a cross spanning 2 tiles from the original place of the bomb, boxes (#3) get destroyed and player (#2) gets hurt.

Specifically:
- [ ] walls (#1) block the explosion
- [ ] box (#3) gets destroyed, but blocks the explosion in that direction onwards
- [ ] player (#2) gets hurt
